### ISSUE TITLE
Dynamic library for Windows

### ISSUE THREAD

**Issue by jhallier** [coin-or/qpOASES#117]
Hi,
currently, a dynamic library for Windows is not supported. As far as I see and have already tried locally, all it takes is to precede the headers of the classes with a 
__declspec(dllexport)
declaration. This could also be activated with a preprocessor directive that can be activated from CMake or the configure scripts. If there is interest, I could prepare a PR with the changes, unless there is some other reason why this was not yet done?

**Comment by traversaro** [comment]
I am not a mantainer of qpOASES, but I would be interested in that. I tried in the past via `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS` (see https://github.com/coin-or/qpOASES/pull/109#issue-574762899), but it was not working due to the presence of static variables. However, using visibility annotations as you propose should work fine.

**Comment by apotschka** [comment]
Thanks! I'd certainly like the feature.

The non-cmake build process currently also has `WIN32` `#define`d in `make_windows.mk`. You should be fine with using something like
```
#ifdef WIN32
__declspec(dllexport)
#endif
```

This could be hidden inside another macro, e.g., named `DLL_EXPORT`.

I'd appreciate your PR.

**Comment by jhallier** [comment]
Ok, I've added a PR for discussion https://github.com/coin-or/qpOASES/pull/118 
Closed this issue here then.
